### PR TITLE
Add base ansible structure

### PR DESCRIPTION
**Pull request by kkirsche**
Add the base ansible roles structure as laid out by:

http://docs.ansible.com/ansible/playbooks_best_practices.html

### CODE REVIEW

**Comment by kkirsche** [comment]
I wanted to follow up and see if there was anything that I needed to address to start moving this project forward. Thanks!

**Comment by mubix** [comment]
@kkirsche was simply surprised by the pull request as I already had everything created and was ready to push it when I saw your pull request. Now the structure you've laid out is simply scaring me off is all. I'll work on putting what I have in a more formal structure but it'll take longer

**Comment by kkirsche** [comment]
If you have stuff done feel free to push it and then others can assist with restructuring it to follow those types of guidelines. In my opinion, I don't think that should be a barrier to pushing it out, and fully understand if you push it out and close this

**Comment by kkirsche** [comment]
Did you give up on this as a result of this...that wasn't at all the goal of this 😞

**Pull request closed without merging**
